#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/.."
. "$PROJECT_ROOT/lib/log.sh"
. "$PROJECT_ROOT/.env"

section "ALLOWLIST: Setup DNS-based filtering with ipset"

WHITELIST_FILE="$PROJECT_ROOT/config/whitelist.txt"
ALLOW_ALL_IPS_FILE="$PROJECT_ROOT/config/allow_all_ips.txt"
DNSMASQ_CONF="/etc/dnsmasq.d/whitelist.conf"

step "Installing required packages"
sudo apt install -y ipset dnsmasq iptables

step "Creating ipsets"
sudo ipset create whitelist hash:ip || true
sudo ipset create allow_all hash:ip || true

step "Generating dnsmasq whitelist config"
echo "# Generated by 08-setup-allowlist.sh" | sudo tee "$DNSMASQ_CONF" > /dev/null
while IFS= read -r domain; do
  echo "ipset=/$domain/whitelist" | sudo tee -a "$DNSMASQ_CONF" > /dev/null
done < "$WHITELIST_FILE"

step "Restarting dnsmasq"
sudo systemctl restart dnsmasq

step "Populating allow_all ipset"
while IFS= read -r ip; do
  sudo ipset add allow_all "$ip" || true
done < "$ALLOW_ALL_IPS_FILE"

step "Setting iptables rules"
sudo iptables -C FORWARD -m set --match-set allow_all src -j ACCEPT 2>/dev/null || \
  sudo iptables -A FORWARD -m set --match-set allow_all src -j ACCEPT

sudo iptables -C FORWARD -m set --match-set whitelist dst -j ACCEPT 2>/dev/null || \
  sudo iptables -A FORWARD -m set --match-set whitelist dst -j ACCEPT

sudo iptables -C FORWARD -j REJECT 2>/dev/null || \
  sudo iptables -A FORWARD -j REJECT

step "Saving ipsets"
sudo ipset save | sudo tee /etc/ipset.conf > /dev/null

step "Installing ipset-restore systemd service"

sudo cp "$PROJECT_ROOT/config/ipset-restore.service" /etc/systemd/system/ipset-restore.service
sudo systemctl daemon-reload
sudo systemctl enable ipset-restore.service

step "Running ipset restore immediately"
sudo systemctl start ipset-restore.service

ok "Allowlist filtering set up successfully"
